#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Lang {
    Es,
    En,
}

pub struct LangStrings {
    pub title: &'static str,
    pub select_option: &'static str,
    pub solid: &'static str,
    pub gradient: &'static str,
    pub solid_mode: &'static str,
    pub gradient_mode: &'static str,
    pub hex_color_hint: &'static str,
    pub color_count: &'static str,
    pub preview: &'static str,
    pub enter_hex_valid: &'static str,
    pub enter_all_hex: &'static str,
    pub invalid_format: &'static str,
    pub invalid_hex: &'static str,
    pub invalid_color: &'static str,
    pub color_applied: &'static str,
    pub gradient_applied: &'static str,
    pub nav_help: &'static str,
    pub apply_help: &'static str,
    pub gradient_help: &'static str,
    pub help_title: &'static str,
    pub help_usage: &'static str,
    pub help_options: &'static str,
    pub help_opt_help: &'static str,
    pub help_opt_version: &'static str,
    pub help_interactive: &'static str,
    pub invalid_arg: &'static str,
    pub lang_select: &'static str,
    pub lang_spanish: &'static str,
    pub lang_english: &'static str,
}

impl Lang {
    pub fn strings(&self) -> LangStrings {
        match self {
            Lang::Es => LangStrings {
                title: "Configurador de colores para Cava",
                select_option: "Selecciona una opcion:",
                solid: "Solido",
                gradient: "Gradiente",
                solid_mode: "  Modo Solido - Color unico para las barras",
                gradient_mode: "  Modo Gradiente - Colores de abajo hacia arriba",
                hex_color_hint: "Color hex (ej: #ffffff): ",
                color_count: "Cantidad de colores:",
                preview: "Vista previa:",
                enter_hex_valid: "Ingresa un color hex valido para ver la vista previa",
                enter_all_hex: "Ingresa todos los colores hex para ver la vista previa",
                invalid_format: "Formato invalido. Usa: #RRGGBB",
                invalid_hex: "Color hex invalido",
                invalid_color: "Color {} invalido (usa #RRGGBB)",
                color_applied: "Color aplicado correctamente!",
                gradient_applied: "Gradiente aplicado correctamente!",
                nav_help: "[Up/Down] Navegar  [Enter] Seleccionar  [Esc] Salir",
                apply_help: "[Enter] Aplicar  [Esc] Volver",
                gradient_help: "[Tab] Siguiente color  [Enter] Aplicar  [Esc] Volver",
                help_title: "BlooCava - Configurador de colores para Cava",
                help_usage: "Uso: bloocava [opciones]",
                help_options: "Opciones:",
                help_opt_help: "  -h, --help     Muestra esta ayuda",
                help_opt_version: "  -v, --version  Muestra la version",
                help_interactive: "Sin argumentos, abre la interfaz interactiva.",
                invalid_arg: "Argumento no valido. Usa -h para ayuda.",
                lang_select: "Idioma / Language:",
                lang_spanish: "Espanol",
                lang_english: "English",
            },
            Lang::En => LangStrings {
                title: "Color configurator for Cava",
                select_option: "Select an option:",
                solid: "Solid",
                gradient: "Gradient",
                solid_mode: "  Solid Mode - Single color for bars",
                gradient_mode: "  Gradient Mode - Colors from bottom to top",
                hex_color_hint: "Hex color (e.g. #ffffff): ",
                color_count: "Number of colors:",
                preview: "Preview:",
                enter_hex_valid: "Enter a valid hex color to see preview",
                enter_all_hex: "Enter all hex colors to see preview",
                invalid_format: "Invalid format. Use: #RRGGBB",
                invalid_hex: "Invalid hex color",
                invalid_color: "Color {} invalid (use #RRGGBB)",
                color_applied: "Color applied successfully!",
                gradient_applied: "Gradient applied successfully!",
                nav_help: "[Up/Down] Navigate  [Enter] Select  [Esc] Exit",
                apply_help: "[Enter] Apply  [Esc] Back",
                gradient_help: "[Tab] Next color  [Enter] Apply  [Esc] Back",
                help_title: "BlooCava - Color configurator for Cava",
                help_usage: "Usage: bloocava [options]",
                help_options: "Options:",
                help_opt_help: "  -h, --help     Show this help",
                help_opt_version: "  -v, --version  Show version",
                help_interactive: "Without arguments, opens the interactive interface.",
                invalid_arg: "Invalid argument. Use -h for help.",
                lang_select: "Language / Idioma:",
                lang_spanish: "Espanol",
                lang_english: "English",
            },
        }
    }
}
